node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 6
          }
          dim {
            size: 6
          }
        }
        tensor_content: "\220\275+\277\351\357d>\026\032L?\026\365\304=8 9?G\036\255>K\345:\277NZi?\332f\002\277\261\220y?\312\223\010\300\303/\032?\300\321\237\276\254\255[\277\325\260\344?\261\3600\277d\026\274>c\300\362\277\331\354\221\275\253\213\255\275\216\314L?B\314\300>\232\032`?\200J\020>\n\030\033?fH\027\300\250g\034?8\262f=-\232D\276WP\354=\330\205M?\214\306\267\277\265\250U\277^]\301=\335\260\214\277\035\311=\276"
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "QuantizeAndDequantizeV2/input_min"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: -1.0
      }
    }
  }
}
node {
  name: "QuantizeAndDequantizeV2/input_max"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 1.0
      }
    }
  }
}
node {
  name: "QuantizeAndDequantizeV2"
  op: "QuantizeAndDequantizeV2"
  input: "in_0/read"
  input: "QuantizeAndDequantizeV2/input_min"
  input: "QuantizeAndDequantizeV2/input_max"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "num_bits"
    value {
      i: 8
    }
  }
  attr {
    key: "range_given"
    value {
      b: true
    }
  }
  attr {
    key: "round_mode"
    value {
      s: "HALF_UP"
    }
  }
  attr {
    key: "signed_input"
    value {
      b: false
    }
  }
}
library {
}
