node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 4
          }
        }
        tensor_content: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "in_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 4
          }
        }
        tensor_content: "\000\000\200@\000\000\200@\000\000\200@\000\000\200@\000\000\200@\000\000\200@\000\000\200@\000\000\200@\000\000\200@\000\000\200@\000\000\200@\000\000\200@"
      }
    }
  }
}
node {
  name: "in_1/read"
  op: "Identity"
  input: "in_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_1"
      }
    }
  }
}
node {
  name: "assert_none_equal/NotEqual"
  op: "NotEqual"
  input: "in_0/read"
  input: "in_1/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "assert_none_equal/Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\000\000\001\000\000\000"
      }
    }
  }
}
node {
  name: "assert_none_equal/All"
  op: "All"
  input: "assert_none_equal/NotEqual"
  input: "assert_none_equal/Const"
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Switch"
  op: "Switch"
  input: "assert_none_equal/All"
  input: "assert_none_equal/All"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/switch_t"
  op: "Identity"
  input: "assert_none_equal/Assert/AssertGuard/Switch:1"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/switch_f"
  op: "Identity"
  input: "assert_none_equal/Assert/AssertGuard/Switch"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/pred_id"
  op: "Identity"
  input: "assert_none_equal/All"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/NoOp"
  op: "NoOp"
  input: "^assert_none_equal/Assert/AssertGuard/switch_t"
}
node {
  name: "assert_none_equal/Assert/AssertGuard/control_dependency"
  op: "Identity"
  input: "assert_none_equal/Assert/AssertGuard/switch_t"
  input: "^assert_none_equal/Assert/AssertGuard/NoOp"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@assert_none_equal/Assert/AssertGuard/switch_t"
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Assert/data_0"
  op: "Const"
  input: "^assert_none_equal/Assert/AssertGuard/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
        }
        string_val: ""
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Assert/data_1"
  op: "Const"
  input: "^assert_none_equal/Assert/AssertGuard/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
        }
        string_val: "Condition x != y did not hold for every single element:"
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Assert/data_2"
  op: "Const"
  input: "^assert_none_equal/Assert/AssertGuard/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
        }
        string_val: "x (in_0/read:0) = "
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Assert/data_4"
  op: "Const"
  input: "^assert_none_equal/Assert/AssertGuard/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
        }
        string_val: "y (in_1/read:0) = "
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Assert"
  op: "Assert"
  input: "assert_none_equal/Assert/AssertGuard/Assert/Switch"
  input: "assert_none_equal/Assert/AssertGuard/Assert/data_0"
  input: "assert_none_equal/Assert/AssertGuard/Assert/data_1"
  input: "assert_none_equal/Assert/AssertGuard/Assert/data_2"
  input: "assert_none_equal/Assert/AssertGuard/Assert/Switch_1"
  input: "assert_none_equal/Assert/AssertGuard/Assert/data_4"
  input: "assert_none_equal/Assert/AssertGuard/Assert/Switch_2"
  attr {
    key: "T"
    value {
      list {
        type: DT_STRING
        type: DT_STRING
        type: DT_STRING
        type: DT_FLOAT
        type: DT_STRING
        type: DT_FLOAT
      }
    }
  }
  attr {
    key: "summarize"
    value {
      i: 3
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Assert/Switch"
  op: "Switch"
  input: "assert_none_equal/All"
  input: "assert_none_equal/Assert/AssertGuard/pred_id"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@assert_none_equal/All"
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Assert/Switch_1"
  op: "Switch"
  input: "in_0/read"
  input: "assert_none_equal/Assert/AssertGuard/pred_id"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Assert/Switch_2"
  op: "Switch"
  input: "in_1/read"
  input: "assert_none_equal/Assert/AssertGuard/pred_id"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_1"
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/control_dependency_1"
  op: "Identity"
  input: "assert_none_equal/Assert/AssertGuard/switch_f"
  input: "^assert_none_equal/Assert/AssertGuard/Assert"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@assert_none_equal/Assert/AssertGuard/switch_f"
      }
    }
  }
}
node {
  name: "assert_none_equal/Assert/AssertGuard/Merge"
  op: "Merge"
  input: "assert_none_equal/Assert/AssertGuard/control_dependency_1"
  input: "assert_none_equal/Assert/AssertGuard/control_dependency"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "in_0/read"
  input: "in_1/read"
  input: "^assert_none_equal/Assert/AssertGuard/Merge"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
