node {
  name: "Variable"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_DOUBLE
        tensor_shape {
          dim {
          }
          dim {
            size: 2
          }
        }
      }
    }
  }
}
node {
  name: "Variable/read"
  op: "Identity"
  input: "Variable"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  }
}
node {
  name: "packed"
  op: "Pack"
  input: "Variable/read"
  attr {
    key: "N"
    value {
      i: 1
    }
  }
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "axis"
    value {
      i: 0
    }
  }
}
node {
  name: "ReduceLogSumExp/Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\000\000\000\000\001\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "ReduceLogSumExp/Max"
  op: "Max"
  input: "packed"
  input: "ReduceLogSumExp/Const"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: true
    }
  }
}
node {
  name: "ReduceLogSumExp/IsFinite"
  op: "IsFinite"
  input: "ReduceLogSumExp/Max"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "ReduceLogSumExp/zeros_like"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_DOUBLE
        tensor_shape {
          dim {
            size: 1
          }
          dim {
            size: 1
          }
          dim {
            size: 1
          }
        }
        double_val: 0.0
      }
    }
  }
}
node {
  name: "ReduceLogSumExp/Select"
  op: "Select"
  input: "ReduceLogSumExp/IsFinite"
  input: "ReduceLogSumExp/Max"
  input: "ReduceLogSumExp/zeros_like"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "ReduceLogSumExp/StopGradient"
  op: "StopGradient"
  input: "ReduceLogSumExp/Select"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "ReduceLogSumExp/Sub"
  op: "Sub"
  input: "packed"
  input: "ReduceLogSumExp/StopGradient"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "ReduceLogSumExp/Exp"
  op: "Exp"
  input: "ReduceLogSumExp/Sub"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "ReduceLogSumExp/Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\000\000\000\000\001\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "ReduceLogSumExp/Sum"
  op: "Sum"
  input: "ReduceLogSumExp/Exp"
  input: "ReduceLogSumExp/Const_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
node {
  name: "ReduceLogSumExp/Log"
  op: "Log"
  input: "ReduceLogSumExp/Sum"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "ReduceLogSumExp/Shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
          }
        }
      }
    }
  }
}
node {
  name: "ReduceLogSumExp/Reshape"
  op: "Reshape"
  input: "ReduceLogSumExp/StopGradient"
  input: "ReduceLogSumExp/Shape"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "Tshape"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "ReduceLogSumExp/Add"
  op: "Add"
  input: "ReduceLogSumExp/Log"
  input: "ReduceLogSumExp/Reshape"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
library {
}
