node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 5
          }
          dim {
            size: 1
          }
          dim {
            size: 4
          }
        }
        tensor_content: "~^G?L\033M?\236p9?\220ol>\356%:?X\2708><q\001?b|d?\224\316\013?\314al?P@\257=,5K?\326\271(?\3566\016?`u#>0\024\236>\240{\036>\240h\360>\222o~?v|\034?"
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "unstack"
  op: "Unpack"
  input: "in_0/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "axis"
    value {
      i: 0
    }
  }
  attr {
    key: "num"
    value {
      i: 5
    }
  }
}
node {
  name: "rnn/BasicRNNCellZeroState/Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "rnn/BasicRNNCellZeroState/Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "rnn/BasicRNNCellZeroState/concat/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "rnn/BasicRNNCellZeroState/concat"
  op: "ConcatV2"
  input: "rnn/BasicRNNCellZeroState/Const"
  input: "rnn/BasicRNNCellZeroState/Const_1"
  input: "rnn/BasicRNNCellZeroState/concat/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rnn/BasicRNNCellZeroState/zeros/Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "rnn/BasicRNNCellZeroState/zeros"
  op: "Fill"
  input: "rnn/BasicRNNCellZeroState/concat"
  input: "rnn/BasicRNNCellZeroState/zeros/Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "index_type"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/kernel"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 7
          }
          dim {
            size: 3
          }
        }
        tensor_content: "\304\322\226\276M\272\236\276&\3170?H\212G>\334|\032\277\255\224\347\2766\345-?\327/\257\276\360\263\365\276 f\032\2750e\240\275\312\201\000\277\220\315:\276\3401\025?\014\353\334>\330x\327>\014\256??\265\272\"\2770\303r>vZ\031\277\036=\027?"
      }
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/kernel/read"
  op: "Identity"
  input: "rnn/basic_rnn_cell/kernel"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/bias"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\000\000\000\000\000\000\000\000\000\000\000\000"
      }
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/bias/read"
  op: "Identity"
  input: "rnn/basic_rnn_cell/bias"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat"
  op: "ConcatV2"
  input: "unstack"
  input: "rnn/BasicRNNCellZeroState/zeros"
  input: "rnn/basic_rnn_cell/concat/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/MatMul"
  op: "MatMul"
  input: "rnn/basic_rnn_cell/concat"
  input: "rnn/basic_rnn_cell/kernel/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/BiasAdd"
  op: "BiasAdd"
  input: "rnn/basic_rnn_cell/MatMul"
  input: "rnn/basic_rnn_cell/bias/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NHWC"
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/Tanh"
  op: "Tanh"
  input: "rnn/basic_rnn_cell/BiasAdd"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat_1/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat_1"
  op: "ConcatV2"
  input: "unstack:1"
  input: "rnn/basic_rnn_cell/Tanh"
  input: "rnn/basic_rnn_cell/concat_1/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/MatMul_1"
  op: "MatMul"
  input: "rnn/basic_rnn_cell/concat_1"
  input: "rnn/basic_rnn_cell/kernel/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/BiasAdd_1"
  op: "BiasAdd"
  input: "rnn/basic_rnn_cell/MatMul_1"
  input: "rnn/basic_rnn_cell/bias/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NHWC"
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/Tanh_1"
  op: "Tanh"
  input: "rnn/basic_rnn_cell/BiasAdd_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat_2/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat_2"
  op: "ConcatV2"
  input: "unstack:2"
  input: "rnn/basic_rnn_cell/Tanh_1"
  input: "rnn/basic_rnn_cell/concat_2/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/MatMul_2"
  op: "MatMul"
  input: "rnn/basic_rnn_cell/concat_2"
  input: "rnn/basic_rnn_cell/kernel/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/BiasAdd_2"
  op: "BiasAdd"
  input: "rnn/basic_rnn_cell/MatMul_2"
  input: "rnn/basic_rnn_cell/bias/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NHWC"
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/Tanh_2"
  op: "Tanh"
  input: "rnn/basic_rnn_cell/BiasAdd_2"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat_3/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat_3"
  op: "ConcatV2"
  input: "unstack:3"
  input: "rnn/basic_rnn_cell/Tanh_2"
  input: "rnn/basic_rnn_cell/concat_3/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/MatMul_3"
  op: "MatMul"
  input: "rnn/basic_rnn_cell/concat_3"
  input: "rnn/basic_rnn_cell/kernel/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/BiasAdd_3"
  op: "BiasAdd"
  input: "rnn/basic_rnn_cell/MatMul_3"
  input: "rnn/basic_rnn_cell/bias/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NHWC"
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/Tanh_3"
  op: "Tanh"
  input: "rnn/basic_rnn_cell/BiasAdd_3"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat_4/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/concat_4"
  op: "ConcatV2"
  input: "unstack:4"
  input: "rnn/basic_rnn_cell/Tanh_3"
  input: "rnn/basic_rnn_cell/concat_4/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/MatMul_4"
  op: "MatMul"
  input: "rnn/basic_rnn_cell/concat_4"
  input: "rnn/basic_rnn_cell/kernel/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/BiasAdd_4"
  op: "BiasAdd"
  input: "rnn/basic_rnn_cell/MatMul_4"
  input: "rnn/basic_rnn_cell/bias/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NHWC"
    }
  }
}
node {
  name: "rnn/basic_rnn_cell/Tanh_4"
  op: "Tanh"
  input: "rnn/basic_rnn_cell/BiasAdd_4"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "stack"
  op: "Pack"
  input: "rnn/basic_rnn_cell/Tanh"
  input: "rnn/basic_rnn_cell/Tanh_1"
  input: "rnn/basic_rnn_cell/Tanh_2"
  input: "rnn/basic_rnn_cell/Tanh_3"
  input: "rnn/basic_rnn_cell/Tanh_4"
  attr {
    key: "N"
    value {
      i: 5
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "axis"
    value {
      i: 0
    }
  }
}
node {
  name: "concat"
  op: "Identity"
  input: "rnn/basic_rnn_cell/Tanh_4"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
