node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 9
          }
          dim {
            size: 3
          }
        }
        tensor_content: "\007\000\000\000\002\000\000\000\t\000\000\000\004\000\000\000\003\000\000\000\003\000\000\000\010\000\000\000\003\000\000\000\004\000\000\000\002\000\000\000\001\000\000\000\004\000\000\000\001\000\000\000\001\000\000\000\006\000\000\000\010\000\000\000\006\000\000\000\010\000\000\000\001\000\000\000\005\000\000\000\001\000\000\000\001\000\000\000\007\000\000\000\004\000\000\000\004\000\000\000\004\000\000\000\010\000\000\000"
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "in_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\003\000\000\000\003\000\000\000\003\000\000\000"
      }
    }
  }
}
node {
  name: "in_1/read"
  op: "Identity"
  input: "in_1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_1"
      }
    }
  }
}
node {
  name: "TensorArray/size"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "TensorArray"
  op: "TensorArrayV3"
  input: "TensorArray/size"
  attr {
    key: "clear_after_read"
    value {
      b: true
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "dynamic_size"
    value {
      b: true
    }
  }
  attr {
    key: "element_shape"
    value {
      shape {
        dim {
          size: 3
        }
        dim {
          size: 3
        }
      }
    }
  }
  attr {
    key: "identical_element_shapes"
    value {
      b: true
    }
  }
  attr {
    key: "tensor_array_name"
    value {
      s: ""
    }
  }
}
node {
  name: "TensorArraySplit/ToInt64"
  op: "Cast"
  input: "in_1/read"
  attr {
    key: "DstT"
    value {
      type: DT_INT64
    }
  }
  attr {
    key: "SrcT"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "Truncate"
    value {
      b: false
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "TensorArraySplit/TensorArraySplitV3"
  op: "TensorArraySplitV3"
  input: "TensorArray"
  input: "in_0/read"
  input: "TensorArraySplit/ToInt64"
  input: "TensorArray:1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "TensorArrayReadV3/index"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "TensorArrayReadV3"
  op: "TensorArrayReadV3"
  input: "TensorArray"
  input: "TensorArrayReadV3/index"
  input: "TensorArraySplit/TensorArraySplitV3"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "TensorArrayReadV3_1/index"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "TensorArrayReadV3_1"
  op: "TensorArrayReadV3"
  input: "TensorArray"
  input: "TensorArrayReadV3_1/index"
  input: "TensorArraySplit/TensorArraySplitV3"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "TensorArrayReadV3_2/index"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "TensorArrayReadV3_2"
  op: "TensorArrayReadV3"
  input: "TensorArray"
  input: "TensorArrayReadV3_2/index"
  input: "TensorArraySplit/TensorArraySplitV3"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
}
library {
}
